### ISSUE TITLE
 Can I use my own CN data with gGnome？

### ISSUE THREAD

**Issue by lirris1** [mskilab-org/gGnome#128]
I'm trying to get my head around the gGnome package and got a bit stuck on the data part. It looks like gGnome usually works with SV and copy number data from remixt, jabba, etc. 
Is Clone-specific data essential for building gGraphs in gGnome？Can I use my own copy number data from other tools like sclust?
 Here's an example of what I have:
chr1    1       2985405     2
chr1    2985406 2998881     1
chr1    2998882 3141059     2
chr1    3141060 3151059     1
chr1    3151060 4395771     2

Would love to know if this works with gGnome. Thanks for the help!

**Comment by mskilab** [comment]
yes you can turn any CN profile of genomic ranges (eg seg file bed file)
that can be converted into a GRanges into a gGraph eg via gG(breaks = cnvj

eg gG(breaks = cnv, juncs = junctions)

where cnv is a GRanges eg imported from tsv using something like cnv =
fread(file)[, .(seqnames = V1, start = V2, end = V3, cn = V4)] %>%
as('GRanges')

and if you have junctions from a bedpe or vcf BND file, imported via
junctions = jJ(bedpe_or_vcf_file)

eg gG(breaks = cnv, juncs = junctions)

but without a graph-based CN caller like remixt, jabba, RCK you will not be
able to (accurately) populate the edges (ie junctions) with copy number

however for a "back of the envelope" balanced genome graph you could use
the function balance with those 👆 inputs to find a balanced graph subject
to your input copy profile as a constrained or the "nearest graph" applying
a loss function around your input copy profile

but I would suggest also just trying jabba :) we have a new nextflow based
containerized pipeline

https://github.com/mskilab-org/nf-jabba
