### ISSUE TITLE
Question about converting gGnome objects to .vcf format. 

### ISSUE THREAD

**Issue by wangxlab** [mskilab-org/gGnome#21]
Hi, 

1) We are trying to read .rds file that we obtained from your lab and converting the gGnome object to .vcf format for the junction breakpoint data.  Please see the example code lines below.  As far as I understand the .rds file is gGnome object and I need to install gGnome package first to read the file.  We can't find R command to convert .rds to .vcf file.  I wonder if you have code to convert gGnome object to .vcf format.  

> library("gGnome")
> RDS_17_T1_31_23564<-readRDS("17_T1_31_23564.rds")     ## it seems that 'readRDS()' is from gGnome package, not basic R function. 
> junctions=RDS_17_T1_31_23564$junctions$breakpoints

2) As far as I know, I should install gGnome successfully first.  But, while installing it, I keep getting error as shown below.  As far as I understand, the packages that I got error below are supposed to be installed with gGnome installation.  I tried to install 'gUtils', 'gTrack', and 'S4Vectors' first, but this doesn't work either.  I wonder if you have some advice. 

  Error: Failed to install 'gGnome' from GitHub:
  Failed to install 'gUtils' from GitHub:
  Failed to install 'S4Vectors' from Bioc:
  Could not find tools necessary to compile a package
  Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.

  Error: Failed to install 'gGnome' from GitHub:
  Failed to install 'gTrack' from GitHub:
  Failed to install 'rtracklayer' from Bioc:
  (converted from warning) cannot remove prior installation of package ‘S4Vectors’

Another error message I got while installing gGnome;

  Installing package into ‘/home/biotech/R/x86_64-pc-linux-gnu-library/4.0’
  (as ‘lib’ is unspecified)
  ERROR: dependencies ‘gTrack’, ‘VariantAnnotation’ are not available for package ‘gGnome’
  removing ‘/home/biotech/R/x86_64-pc-linux-gnu-library/4.0/gGnome’
  There were 12 warnings (use warnings() to see them)

Thank you, 
Sanghoon

**Comment by xtYao** [comment]
Which R version are you using? Could you paste the `sessionInfo()` here?

**Comment by xtYao** [comment]
@wangxlab please also try manually install gTrack and rtracklayer by:
`devtools::install_github("mskilab/gTrack")` and `BiocManager::install("rtracklayer")`
